[project]
name = "ctf-utils"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.11.13",
    "cryptography>=44.0.2",
    "numpy>=2.2.3",
    "ugrapheme>=0.8",
    "wcwidth>=0.2.13",
]
